<a href="https://colab.research.google.com/github/six-choi/crawler/blob/main/apirest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup as bs

In [6]:
#판다스 버전 확인
pd.__version__
# 최신 버전으로 판다스 업그레이드
!pip install --upgrade pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
# 인증키(보안을 위해 비식별 처리하였습니다.)
auth_key = "..n# 발급받은 인증키를 요청할 url에 담기
# 최대한 많은 데이터를 수집하기 위해 1부터 999페이지까지 수집하는 것으로 변경
faq_url = f"https://apis.data.go.kr/9760000/VoteXmntckInfoInqireService2/getVoteSttusInfoInqire?sgId=20220309&sgTypecode=1&sdName=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C&pageNo=1&numOfRows=100&resultType=xml&serviceKey={auth_key}"

In [4]:
result = requests.get(faq_url)
print(result.text)

<?xml version="1.0" encoding="UTF-8"?><response>
<header>
<resultCode>INFO-00</resultCode>
<resultMsg>NORMAL SERVICE</resultMsg>
</header>
<body>
<items>
  <item>
    <num>1</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>합계</wiwName>
    <totSunsu>8346647</totSunsu>
    <psSunsu>5151633</psSunsu>
    <psEtcSunsu>3195014</psEtcSunsu>
    <totTusu>6501831</totTusu>
    <psTusu>3328090</psTusu>
    <psEtcTusu>3173741</psEtcTusu>
    <turnout>77.9</turnout>
    <vrOrder>2</vrOrder>
  </item>
  <item>
    <num>2</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>종로구</wiwName>
    <totSunsu>129968</totSunsu>
    <psSunsu>74848</psSunsu>
    <psEtcSunsu>55120</psEtcSunsu>
    <totTusu>100629</totTusu>
    <psTusu>46010</psTusu>
    <psEtcTusu>54619</psEtcTusu>
    <turnout>77.4</turnout>
    <vrOrder>3</vrOrder>
  </item>
  <item>
    <num>3</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>중구</wiwName>
    <totSunsu>111448</totSunsu>
    <psSunsu>67560</psSunsu>
    <psEtcSunsu>43888</psEtcSunsu>
    <totTusu>84998</totTusu>
    <psTusu>41582</psTusu>
    <psEtcTusu>43416</psEtcTusu>
    <turnout>76.3</turnout>
    <vrOrder>4</vrOrder>
  </item>
  <item>
    <num>4</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>용산구</wiwName>
    <totSunsu>199077</totSunsu>
    <psSunsu>120179</psSunsu>
    <psEtcSunsu>78898</psEtcSunsu>
    <totTusu>152068</totTusu>
    <psTusu>74093</psTusu>
    <psEtcTusu>77975</psEtcTusu>
    <turnout>76.4</turnout>
    <vrOrder>5</vrOrder>
  </item>
  <item>
    <num>5</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>성동구</wiwName>
    <totSunsu>252087</totSunsu>
    <psSunsu>154998</psSunsu>
    <psEtcSunsu>97089</psEtcSunsu>
    <totTusu>197240</totTusu>
    <psTusu>100822</psTusu>
    <psEtcTusu>96418</psEtcTusu>
    <turnout>78.2</turnout>
    <vrOrder>6</vrOrder>
  </item>
  <item>
    <num>6</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>광진구</wiwName>
    <totSunsu>303582</totSunsu>
    <psSunsu>185922</psSunsu>
    <psEtcSunsu>117660</psEtcSunsu>
    <totTusu>235471</totTusu>
    <psTusu>118484</psTusu>
    <psEtcTusu>116987</psEtcTusu>
    <turnout>77.6</turnout>
    <vrOrder>7</vrOrder>
  </item>
  <item>
    <num>7</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>동대문구</wiwName>
    <totSunsu>300928</totSunsu>
    <psSunsu>191891</psSunsu>
    <psEtcSunsu>109037</psEtcSunsu>
    <totTusu>232106</totTusu>
    <psTusu>123748</psTusu>
    <psEtcTusu>108358</psEtcTusu>
    <turnout>77.1</turnout>
    <vrOrder>8</vrOrder>
  </item>
  <item>
    <num>8</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>중랑구</wiwName>
    <totSunsu>347108</totSunsu>
    <psSunsu>218838</psSunsu>
    <psEtcSunsu>128270</psEtcSunsu>
    <totTusu>260862</totTusu>
    <psTusu>133148</psTusu>
    <psEtcTusu>127714</psEtcTusu>
    <turnout>75.2</turnout>
    <vrOrder>9</vrOrder>
  </item>
  <item>
    <num>9</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>성북구</wiwName>
    <totSunsu>375880</totSunsu>
    <psSunsu>226017</psSunsu>
    <psEtcSunsu>149863</psEtcSunsu>
    <totTusu>292187</totTusu>
    <psTusu>143209</psTusu>
    <psEtcTusu>148978</psEtcTusu>
    <turnout>77.7</turnout>
    <vrOrder>10</vrOrder>
  </item>
  <item>
    <num>10</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>강북구</wiwName>
    <totSunsu>268974</totSunsu>
    <psSunsu>167966</psSunsu>
    <psEtcSunsu>101008</psEtcSunsu>
    <totTusu>199448</totTusu>
    <psTusu>98912</psTusu>
    <psEtcTusu>100536</psEtcTusu>
    <turnout>74.2</turnout>
    <vrOrder>11</vrOrder>
  </item>
  <item>
    <num>11</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>도봉구</wiwName>
    <totSunsu>281812</totSunsu>
    <psSunsu>179887</psSunsu>
    <psEtcSunsu>101925</psEtcSunsu>
    <totTusu>216036</totTusu>
    <psTusu>114637</psTusu>
    <psEtcTusu>101399</psEtcTusu>
    <turnout>76.7</turnout>
    <vrOrder>12</vrOrder>
  </item>
  <item>
    <num>12</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>노원구</wiwName>
    <totSunsu>441879</totSunsu>
    <psSunsu>277491</psSunsu>
    <psEtcSunsu>164388</psEtcSunsu>
    <totTusu>349297</totTusu>
    <psTusu>185723</psTusu>
    <psEtcTusu>163574</psEtcTusu>
    <turnout>79</turnout>
    <vrOrder>13</vrOrder>
  </item>
  <item>
    <num>13</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>은평구</wiwName>
    <totSunsu>417391</totSunsu>
    <psSunsu>254919</psSunsu>
    <psEtcSunsu>162472</psEtcSunsu>
    <totTusu>317971</totTusu>
    <psTusu>156472</psTusu>
    <psEtcTusu>161499</psEtcTusu>
    <turnout>76.2</turnout>
    <vrOrder>14</vrOrder>
  </item>
  <item>
    <num>14</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>서대문구</wiwName>
    <totSunsu>269615</totSunsu>
    <psSunsu>164216</psSunsu>
    <psEtcSunsu>105399</psEtcSunsu>
    <totTusu>210460</totTusu>
    <psTusu>105828</psTusu>
    <psEtcTusu>104632</psEtcTusu>
    <turnout>78.1</turnout>
    <vrOrder>15</vrOrder>
  </item>
  <item>
    <num>15</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>마포구</wiwName>
    <totSunsu>324091</totSunsu>
    <psSunsu>197654</psSunsu>
    <psEtcSunsu>126437</psEtcSunsu>
    <totTusu>256218</totTusu>
    <psTusu>130785</psTusu>
    <psEtcTusu>125433</psEtcTusu>
    <turnout>79.1</turnout>
    <vrOrder>16</vrOrder>
  </item>
  <item>
    <num>16</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>양천구</wiwName>
    <totSunsu>378710</totSunsu>
    <psSunsu>230746</psSunsu>
    <psEtcSunsu>147964</psEtcSunsu>
    <totTusu>301379</totTusu>
    <psTusu>154244</psTusu>
    <psEtcTusu>147135</psEtcTusu>
    <turnout>79.6</turnout>
    <vrOrder>17</vrOrder>
  </item>
  <item>
    <num>17</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>강서구</wiwName>
    <totSunsu>504185</totSunsu>
    <psSunsu>316548</psSunsu>
    <psEtcSunsu>187637</psEtcSunsu>
    <totTusu>390247</totTusu>
    <psTusu>203639</psTusu>
    <psEtcTusu>186608</psEtcTusu>
    <turnout>77.4</turnout>
    <vrOrder>18</vrOrder>
  </item>
  <item>
    <num>18</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>구로구</wiwName>
    <totSunsu>348156</totSunsu>
    <psSunsu>219683</psSunsu>
    <psEtcSunsu>128473</psEtcSunsu>
    <totTusu>272920</totTusu>
    <psTusu>145070</psTusu>
    <psEtcTusu>127850</psEtcTusu>
    <turnout>78.4</turnout>
    <vrOrder>19</vrOrder>
  </item>
  <item>
    <num>19</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>금천구</wiwName>
    <totSunsu>208786</totSunsu>
    <psSunsu>134616</psSunsu>
    <psEtcSunsu>74170</psEtcSunsu>
    <totTusu>157035</totTusu>
    <psTusu>83196</psTusu>
    <psEtcTusu>73839</psEtcTusu>
    <turnout>75.2</turnout>
    <vrOrder>20</vrOrder>
  </item>
  <item>
    <num>20</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>영등포구</wiwName>
    <totSunsu>334361</totSunsu>
    <psSunsu>206993</psSunsu>
    <psEtcSunsu>127368</psEtcSunsu>
    <totTusu>263581</totTusu>
    <psTusu>137006</psTusu>
    <psEtcTusu>126575</psEtcTusu>
    <turnout>78.8</turnout>
    <vrOrder>21</vrOrder>
  </item>
  <item>
    <num>21</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>동작구</wiwName>
    <totSunsu>342248</totSunsu>
    <psSunsu>199419</psSunsu>
    <psEtcSunsu>142829</psEtcSunsu>
    <totTusu>271510</totTusu>
    <psTusu>129628</psTusu>
    <psEtcTusu>141882</psEtcTusu>
    <turnout>79.3</turnout>
    <vrOrder>22</vrOrder>
  </item>
  <item>
    <num>22</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>관악구</wiwName>
    <totSunsu>446161</totSunsu>
    <psSunsu>271100</psSunsu>
    <psEtcSunsu>175061</psEtcSunsu>
    <totTusu>340773</totTusu>
    <psTusu>166574</psTusu>
    <psEtcTusu>174199</psEtcTusu>
    <turnout>76.4</turnout>
    <vrOrder>23</vrOrder>
  </item>
  <item>
    <num>23</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>서초구</wiwName>
    <totSunsu>344756</totSunsu>
    <psSunsu>213177</psSunsu>
    <psEtcSunsu>131579</psEtcSunsu>
    <totTusu>277878</totTusu>
    <psTusu>147823</psTusu>
    <psEtcTusu>130055</psEtcTusu>
    <turnout>80.6</turnout>
    <vrOrder>24</vrOrder>
  </item>
  <item>
    <num>24</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>강남구</wiwName>
    <totSunsu>451970</totSunsu>
    <psSunsu>289137</psSunsu>
    <psEtcSunsu>162833</psEtcSunsu>
    <totTusu>354778</totTusu>
    <psTusu>193890</psTusu>
    <psEtcTusu>160888</psEtcTusu>
    <turnout>78.5</turnout>
    <vrOrder>25</vrOrder>
  </item>
  <item>
    <num>25</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>송파구</wiwName>
    <totSunsu>565840</totSunsu>
    <psSunsu>343166</psSunsu>
    <psEtcSunsu>222674</psEtcSunsu>
    <totTusu>453536</totTusu>
    <psTusu>232439</psTusu>
    <psEtcTusu>221097</psEtcTusu>
    <turnout>80.2</turnout>
    <vrOrder>26</vrOrder>
  </item>
  <item>
    <num>26</num>
    <sgId>20220309</sgId>
    <sgTypecode>1</sgTypecode>
    <sdName>서울특별시</sdName>
    <wiwName>강동구</wiwName>
    <totSunsu>397634</totSunsu>
    <psSunsu>244662</psSunsu>
    <psEtcSunsu>152972</psEtcSunsu>
    <totTusu>313203</totTusu>
    <psTusu>161128</psTusu>
    <psEtcTusu>152075</psEtcTusu>
    <turnout>78.8</turnout>
    <vrOrder>27</vrOrder>
  </item>
</items>
<numOfRows>100</numOfRows>
<pageNo>1</pageNo>
<totalCount>26</totalCount>
</body>
</response>

In [8]:
df_list_all = pd.read_xml(result.text, xpath=".//item")
df_list_all

,num,sgId,sgTypecode,sdName,wiwName,totSunsu,psSunsu,psEtcSunsu,totTusu,psTusu,psEtcTusu,turnout,vrOrder
0,1,20220309,1,서울특별시,합계,8346647,5151633,3195014,6501831,3328090,3173741,77.9,2
1,2,20220309,1,서울특별시,종로구,129968,74848,55120,100629,46010,54619,77.4,3
2,3,20220309,1,서울특별시,중구,111448,67560,43888,84998,41582,43416,76.3,4
3,4,20220309,1,서울특별시,용산구,199077,120179,78898,152068,74093,77975,76.4,5
4,5,20220309,1,서울특별시,성동구,252087,154998,97089,197240,100822,96418,78.2,6
5,6,20220309,1,서울특별시,광진구,303582,185922,117660,235471,118484,116987,77.6,7
6,7,20220309,1,서울특별시,동대문구,300928,191891,109037,232106,123748,108358,77.1,8
7,8,20220309,1,서울특별시,중랑구,347108,218838,128270,260862,133148,127714,75.2,9
8,9,20220309,1,서울특별시,성북구,375880,226017,149863,292187,143209,148978,77.7,10
9,10,20220309,1,서울특별시,강북구,268974,167966,101008,199448,98912,100536,74.2,11
10,11,20220309,1,서울특별시,도봉구,281812,179887,101925,216036,114637,101399,76.7,12
11,12,20220309,1,서울특별시,노원구,441879,277491,164388,349297,185723,163574,79.0,13
12,13,20220309,1,서울특별시,은평구,417391,254919,162472,317971,156472,161499,76.2,14
13,14,20220309,1,서울특별시,서대문구,269615,164216,105399,210460,105828,104632,78.1,15
14,15,20220309,1,서울특별시,마포구,324091,197654,126437,256218,130785,125433,79.1,16
15,16,20220309,1,서울특별시,양천구,378710,230746,147964,301379,154244,147135,79.6,17
16,17,20220309,1,서울특별시,강서구,504185,316548,187637,390247,203639,186608,77.4,18
17,18,20220309,1,서울특별시,구로구,348156,219683,128473,272920,145070,127850,78.4,19
18,19,20220309,1,서울특별시,금천구,208786,134616,74170,157035,83196,73839,75.2,20
19,20,20220309,1,서울특별시,영등포구,334361,206993,127368,263581,137006,126575,78.8,21
20,21,20220309,1,서울특별시,동작구,342248,199419,142829,271510,129628,141882,79.3,22
21,22,20220309,1,서울특별시,관악구,446161,271100,175061,340773,166574,174199,76.4,23
22,23,20220309,1,서울특별시,서초구,344756,213177,131579,277878,147823,130055,80.6,24
23,24,20220309,1,서울특별시,강남구,451970,289137,162833,354778,193890,160888,78.5,25
24,25,20220309,1,서울특별시,송파구,565840,343166,222674,453536,232439,221097,80.2,26
25,26,20220309,1,서울특별시,강동구,397634,244662,152972,313203,161128,152075,78.8,27